# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

stages:
  - build
  - lint
  - format

variables:
  CCACHE_DIR: $CI_PROJECT_DIR/.cache/ccache

.ccache:
  cache:
    key: ccache-$CI_JOB_IMAGE
    paths:
      - $CCACHE_DIR/
    when: always

.python-venv:
  cache:
    - key: pip-cache
      paths:
        - $PIP_CACHE_DIR/
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip

.python-3.11:
  image: tollerort.desy.de/hub.docker.com/python:3.11

.cnstln-ci-img:
  image: gitlab.desy.de:5555/constellation/constellation/constellation_ci:nightly

# build stage, including linting with clang-tidy

build-cpp:
  extends:
    - .ccache
    - .cnstln-ci-img
  stage: build
  script:
    - cmake -G "Ninja" -B build -DCMAKE_CXX_CLANG_TIDY="clang-tidy" .
    - cmake --build build
  artifacts:
    paths:
      - build
    expire_in: 24 hour

# format stage

.format:
  stage: format
  needs: []

format:clang-format:
  extends:
    - .format
    - .cnstln-ci-img
  script:
    - clang-format --Werror --dry-run *.cpp *.hpp

format:reuse:
  extends: .format
  image: tollerort.desy.de/hub.docker.com/fsfe/reuse:latest
  script:
    - reuse lint

format:codespell:
  extends:
    - .format
    - .python-venv
    - .python-3.11
  script:
    - pip install codespell
    - codespell
